### ISSUE TITLE
ansible-doc fails to print module documentation

### ISSUE THREAD

**Issue by vikentiik** [ViaSat/ansible-vsphere#9]
ansible-doc seem to fail to process the colons in documentation string of the module:

```
#  ansible-doc vsphere
Traceback (most recent call last):
  File "/home/vikentiik/.pyenv/versions/infi/lib/python2.7/site-packages/ansible-1.8.2-py2.7.egg/ansible/utils/module_docs.py", line 54, in get_docstring
    doc = yaml.safe_load(child.value.s)
  File "build/bdist.linux-x86_64/egg/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "build/bdist.linux-x86_64/egg/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "build/bdist.linux-x86_64/egg/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "build/bdist.linux-x86_64/egg/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "build/bdist.linux-x86_64/egg/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "build/bdist.linux-x86_64/egg/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "build/bdist.linux-x86_64/egg/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "build/bdist.linux-x86_64/egg/yaml/scanner.py", line 580, in fetch_value
    self.get_mark())
ScannerError: mapping values are not allowed here
  in "<string>", line 32, column 38:
     ...          Accepted parameters are:
                                         ^
ERROR: module vsphere missing documentation (or could not parse documentation)

```

**Comment by tkinz27** [comment]
So the latest commit ( ff2b342a6ee4fc5afe0302c83115eb33c10c5341 ) should at least fix the syntax issues with ansible-doc. I am going to leave the issue open though, because the formatting of the docs are pretty poor. I just do not have time currently to figure out how to fix it.
